---
- name: Read storage config
  ansible.builtin.command: "pvesh get /storage/{{ terraform_init_storage }} --output-format json"
  register: terraform_init_pvesm
  changed_when: false
  check_mode: false

- name: Set storage content types
  ansible.builtin.command:
    argv:
      - pvesm
      - set
      - "{{ terraform_init_storage }}"
      - --content
      - "{{ terraform_init_storage_content | join(',') }}"
  vars:
    _current: "{{ (terraform_init_pvesm.stdout | from_json).content | default('') | split(',') | sort }}"
  when: _current != (terraform_init_storage_content | sort)