[thinkcentre]
thinkcentre ansible_host=thinkcentre ansible_user=server hostname=thinkcentre

[proxmox]
proxmox-01 ansible_host=192.168.0.250 ansible_user=root

[production]
debian-production ansible_host=production ansible_user=server

[dev]
debian-dev ansible_host=dev ansible_user=server