[thinkcentre]
thinkcentre ansible_host=thinkcentre ansible_user=server hostname=thinkcentre

[proxmox]
proxmox-01 ansible_host=192.168.0.250 ansible_user=root

[debian-test]
debian-test ansible_host=debian-01 ansible_user=server
