---
- name: Initial Fedora config
  hosts: "{{target}}"
  become: true

  vars_prompt:
  - name: target
    prompt: "Which host should this run against?"
    private: false

  roles:
    - update-fedora
    - docker-fedora
    - nfs-mount