---
- name: Run apt update and upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_stat

- name: Set reboot_required
  ansible.builtin.set_fact:
    reboot_required: "{{ reboot_stat.stat.exists }}"